events {
    worker_connections 4096;
}

http {
    # Definimos el grupo de servidores usando la IP de la Máquina 2 (Workers)
    upstream backend_servers {
        server 172.31.18.128:8000;

        # Si en el futuro escalas clonando la máquina de workers,
        # añadirías las nuevas IPs aquí abajo:
        # server IP_MAQUINA_WORKERS_2:8000;
    }

    server {
        listen 80;

        location / {
            # Apuntamos directamente al upstream definido arriba
            proxy_pass http://backend_servers;

            # Cabeceras proxy estándar
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Tiempos de espera
            proxy_connect_timeout 10s;
            proxy_read_timeout 30s;
        }
    }
}