# Permitir conexiones desde cualquier IP (necesario para entornos multi-MV)
bind 0.0.0.0

# Desactivar el modo protegido para permitir el acceso externo sin contraseña
protected-mode no

# Puerto por defecto
port 6379